apiVersion: v1
kind: Service
metadata:
  name: {{ include "awesomecat.fullname" . }}-backend-service
  labels:
  {{- include "awesomecat.labels" . | nindent 4 }}
spec:
  type: {{ .Values.backendService.type }}
  selector:
    component: back
  {{- include "awesomecat.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.backendService.ports | toYaml | nindent 2 -}}