apiVersion: v1
kind: Service
metadata:
  name: {{ include "awesomecat.fullname" . }}-frontend-service
  labels:
  {{- include "awesomecat.labels" . | nindent 4 }}
spec:
  type: {{ .Values.frontendService.type }}
  selector:
    component: front
  {{- include "awesomecat.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.frontendService.ports | toYaml | nindent 2 -}}