apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "awesomecat.fullname" . }}-ingress-gcp-team
  labels:
  {{- include "awesomecat.labels" . | nindent 4 }}
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  rules:
  - http:
      paths:
      - backend:
          service:
            name: '{{ include "awesomecat.fullname" . }}-frontend-service'
            port:
              number: 80
        path: /?(.*)
        pathType: Prefix
      - backend:
          service:
            name: '{{ include "awesomecat.fullname" . }}-backend-service'
            port:
              number: 3000
        path: /api/?(.*)
        pathType: Prefix