apiVersion: v1
kind: Secret
metadata:
  name: {{ include "awesomecat.fullname" . }}-postgres-secret
  labels:
  {{- include "awesomecat.labels" . | nindent 4 }}
data:
  PGDATABASE: {{ required "postgresSecret.pgdatabase is required" .Values.postgresSecret.pgdatabase
    | b64enc | quote }}
  PGHOST: {{ required "postgresSecret.pghost is required" .Values.postgresSecret.pghost
    | b64enc | quote }}
  PGPASSWORD: {{ required "postgresSecret.pgpassword is required" .Values.postgresSecret.pgpassword
    | b64enc | quote }}
  PGUSER: {{ required "postgresSecret.pguser is required" .Values.postgresSecret.pguser
    | b64enc | quote }}