apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hello-web-disk-zhss
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: demo-storage
  resources:
    requests:
      storage: 1Gi