apiVersion: cert-manager.io/v1                             
kind: ClusterIssuer                             
metadata:                               
  name: letsencrypt-cluster-issuer                             
spec:                            
  acme:                                 
    server: https://acme-v02.api.letsencrypt.org/directory
    email: zhakyp.zhommartuuluu@email.com
    privateKeySecretRef:                                                                   
      name: letsencrypt-cluster-issuer-key
    solvers:
    - http01:
        ingress:
          class: nginx

---

apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: example-cert  #name of this object
  namespace: default #same namespace as 
spec:
  dnsNames:
    - anttech.online
  secretName: example-tls-cert
  issuerRef:
    name: letsencrypt-cluster-issuer
    kind: ClusterIssuer