apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-dep-1
  namespace: zhakyp1
spec:
  selector:
    matchLabels:
      greeting: hello
      version: one
  replicas: 1
  template: 
    metadata:
      labels:
        greeting: hello
        version: one
    spec:
      containers:
      - name: hello-app-1
        image: nginx:1.23.3
        command: ["sh", "-c",  "echo Hi it is worked 1 > /usr/share/nginx/html/index.html && nginx -g 'daemon off;'"]
        env:
        - name: "PORT"
          value: "80"

---
apiVersion: v1
kind: Service
metadata: 
  name: hello-world-1
  namespace: zhakyp1
spec:
  # type: LoadBalancer
  selector:
    greeting: hello
    version: one
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-dep-2
  namespace: zhakyp1
spec:
  selector:
    matchLabels:
      greeting: hello
      version: two
  replicas: 1
  template:
    metadata:
      labels:
        greeting: hello
        version: two
    spec:
      containers:
      - name: hello-app-2
        image: nginx:1.23.3
        command: ["sh", "-c",  "echo Hi it is worked > /usr/share/nginx/html/index.html && nginx -g 'daemon off;'"]
        env: 
        - name: "PORT"
          value: "80"

---
apiVersion: v1
kind: Service
metadata:
  name: hello-world-2
  namespace: zhakyp1
spec:
  # type: LoadBalancer
  selector:
    greeting: hello
    version: two
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: my-ingress
  namespace: zhakyp1
  annotations:
    # external-dns.alpha.kubernetes.io/hostname: hello-world-2.ns.akzhol7.ml.
    nginx.ingress.kubernetes.io/rewrite-target: / 
    kubernetes.io/ingress.class: "nginx" 
    # cert-manager.io/issuer: "letsencrypt-staging" 
    
spec:
  tls:
  - hosts:
    - ns.bakai4kg.gq
    secretName: zhakyp-tls-secret
  rules:
  - host: ns.bakai4kg.gq
    http:
      paths:
      - path: /first
        pathType: Prefix
        backend: 
          service:
            name: hello-world-1
            port:
              number: 80
      - path: /second
        pathType: Prefix
        backend:
          service:
            name: hello-world-2
            port:
              number: 80
