apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: c-issuer
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: zhakyp.zhoomartuuluu@gmail.com
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
    - http01:
        ingress:
          class: nginx